#+TITLE: Bootcamp plan
#+AUTHOR: VLEAD
#+DATE: [2018-04-23 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document describes the bootcamp plan for selected students at
  IIITH. VLEAD would be conducting the 3 days bootcamp for the
  students to onboard them for the next 3-4 weeks of the internship
  program. They would be trained on the development/testing
  environments along with the technological dependencies required for
  the labs.
* Venue, Date and Time
  - Venue : IIIT-Hyderabad
  - Start Date : 09-05-2018
  - End Date : 11-05-2018
  - Time : 10:00 AM to 04:00 PM
* Participants
  - Shortlisted candidates from the [[https://github.com/vlead/outreach-internship-program/blob/develop/src/index.org#phase-1---issuebug-logging-process-selection-of-interns][Phase 1/Validation process]]
* Goals
  - Understand and follow the development process.
  - Fixing the issues/bugs/defects which were found during
    [[https://github.com/vlead/outreach-internship-program/blob/develop/src/index.org#phase-1---issuebug-logging-process-selection-of-interns][Phase 1/Validation process]]
* Integration Document
  [[][Link for document]]
* Plan of action
  - Day 1
    10:00 AM - Welcome address /Introduction
    10:30 AM - Discussion about the tasks to be done during
    the 3 week process of internship.
    11:00 AM - Setup the development environment for fixing
    the bugs.
    01:00 PM - LUNCH
    02:00 PM - A brief description about the github and the
    process of use and make a commit after the code fix is
    done. 
    
    Reference : Github link for the lab code repositories
    Please use this [[https://github.com/virtual-labs/][link]] for the IIIT-Hyderabad labs code
    repositories for testing. The 20 IIIT hyderabad labs
    which needs to be tested would have a naming convention
    of *<labname>-iiith* 
    
  - Day 2 
    10:00 AM - Description about the Java and JavaScript
    dependencies for fixing the bugs.
    11:30 AM - A brief description about the process of
    resolving the issues
    01:00 PM - LUNCH
    02:00 PM - Students work on fixing bugs.
 
  - Day 3
    10:00 AM - Any assistance needed in resolving bugs.
    11:15 AM - Testing the fixed bugs 
    01:00 PM - LUNCH
    02:00 PM - Steps to create a pull request in git
    04:00 PM - A quick recap for the bug fixing process. 


* Prerequisites for the participants
  - OS?
  - emacs?
  - Setup git 
* Post-workshop Activities
  Refer the document for [[][Document]]
* Evaluation Criteria 
  Based on the severity level of the issue, points would be
  given. 
  - S1 issue is awarded with 5 Points
  - S2 issue is awarded with 3 Points
  - S3 issue is awarded with 1 Point
* Contact Information
  Please contact the VLEAD Team at internship@vlabs.ac.in
* Conclusion
  After the validation process, the issues would be
  finalized and assigned to the students for resolving them.
  




