#+TITLE: Outreach Intership Program 
#+AUTHOR: VLEAD
#+DATE: [2018-04-17 Tue]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Draft e-mail for Virtual Labs Outreach Internship Program

Dear Nodal Coordinators,

Welcome to Virtual Labs Internship @ IIITH !!!

We are delighted that your students are interested to participate in
the [[https://vlabs.ac.in][Virtual Labs]] 2018 Internship Program. This program has been
exclusively developed to provide students a good understanding in open
source technologies, software development life cycle while working
with technology experts and simultaneously contribute to the
elimination of bugs and thereby improving the quality of the labs.


All the nodal coordinators are requested to forward the following mail
to your 2nd and 3rd year BTech/MCA/Mtech students from CSE (Computer
Science and Engineering), ECE (Electronics and Communication
Engineering), CE (Civil Engineering) and Chemical Sciences branches.

==========================================================================================

Dear Students,

Virtual Labs (an MHRD initiative @ IIITH) is offering internships for
the students who are seeking an opportunity to get an insight of the
software development processes to help them improve their problem
solving skills.

About the program

This program has been exclusively developed to provide students a good
understanding in open source technologies, software development life
cycle while working with technology experts.  

The program is designed in 2 phases :

1) Phase 1 - Selection of interns 
   
   To apply for the internship program, make sure you have your [[https://about.gitlab.com/about/][GitLab]]
   handle and a resume available online. The selection process would
   be based on the initial activity of logging bugs by the applied
   students. The step by step instructions are provided in this
   [[https://github.com/vlead/outreach-internship-program/blob/develop/src/index.org#issuebug-logging-process---selection-of-interns][document]].

   Duration for bug logging by the students is allowed till 5th May
   2018 , 12:00 A.M. IST.  We would request all the interested
   students to fill the form below after they have logged the bugs in
   their gitlab profiles.

   [[https://docs.google.com/forms/d/e/1FAIpQLSdhl1KOzr_v0Sz15bVxKHuYdlluODnAKku11W1WDWLft5JgPg/viewform][Internship Application Form]]  


   The deadline for applications is May 6th 2018, 12:00 A.M. IST


2) Phase 2 - Internship process

   Based on our review of the bugs logged, interns would be selected
   and called for a 3 days Bootcamp (9th-11th May, 2018 tentative) at
   IIITH. For this process also we would provide the interns with step
   by step instructions after they are onboarded.


Takeaways

1) Top 10 students will be awarded with cash prize based on the number
   and type of issues (severity level, functionality defects, proposal
   for enhancements and logical flaws) logged by them during the
   selection process.

2) The selected interns would be weekly reviewed at IIIT H and the top
   contributors in a week will be awarded with surprise gifts.

3) Top 3 interns at the end of the program would be awarded with cash
   prizes.

4) All the interns contributing in code fixes would get an
   internship certificate.
 
   
Wishing you all the best and we look forward for your successful
internship. For any clarifications, please contact :

2018-summer-interns@vlabs.ac.in

