#+TITLE: Outreach Intership Program 
#+AUTHOR: VLEAD
#+DATE: [2018-04-17 Tue]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Draft mail calling for interns
Dear Students,


Virtual Labs is offering internships for the students who
are seeking an opportunity to get an insight of the software
development processes to help them improve their problem
solving skills.

We would request all the interested students to fill the
expression of interest form below.

[[https://docs.google.com/forms/d/e/1FAIpQLSdhl1KOzr_v0Sz15bVxKHuYdlluODnAKku11W1WDWLft5JgPg/viewform][Expression of interest]]  


The deadline for applications for internships is Apr 24th 2018.

Sincerely,

Venkatesh Choppella, Ph.D
Associate Professor
IIIT Hyderabad
Gachibowli, Hyderabad 500 032
http://pascal.iiit.ac.in/~choppell





-- 
Regards
Priya

* Draft e-mail for Virtual Labs Outreach Internship Program

Dear Nodal Coordinators,

Welcome to Virtual Labs Internship @ IIITH !!!

We are delighted that you are interested to participate in the [[https://vlabs.ac.in][Virtual
Labs]] Internship Program. It has been developed to provide students a
good understanding in open source technologies, software development
life cycle and working with technology experts.

Following are the instructions for students to participate in the
selection process of internship.

1) The students would be shortlisted based on the number and type of
   [[https://help.github.com/articles/about-issues/][issues]] raised in their [[https://about.gitlab.com/about/][GitLab]] profile for the 20 [[https://vlabs.ac.in][IIIT-Hyderabad]]
   labs. Based on the issues raised the students would be given an
   opportunity to work as a intern in Virtual Labs.

2) [[https://github.com/vlead/outreach-internship-program/blob/develop/src/index.org#setup-of-testing-environment][Click here]] to see the detailed steps for the issue raising process
   and setting up the local testing environment.

3) Duration for defect logging by the students is allowed till 5th May
   2018 , 12:00 A.M. IST.

4) Top 10 students will be awarded with cash prize based on the number
   and type of issues (severity level, functionality defects, proposal
   for enhancements and logical flaws).

5) Selected students would get an opportunity to attend a 3 days boot
   camp (9th-11th May, 2018) at IIIT-Hyderabad headed by our esteemed
   faculty and mentors. On the first day, students would be mentored
   on GitHub and development processes, followed by the next one day
   session on the required technological competencies. The last day
   would be focussed on a sample issue demo along with the Validation
   and Review process.
   
6) The interns would be weekly reviewed at IIIT H and the top
   contributors in a week will be awarded with surprise gifts. 

7) Top 3 interns at the end of the program would be awarded with cash
   prizes. All the interns contributing in code fixes would get an
   internship certificate.
 
Wishing you all the best and we look forward for your successful
internship. For any clarifications, please contact <email id>



