#+TITLE: Story Board for Outreach Internship Program
#+AUTHOR: VLEAD
#+DATE: [2018-04-12 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document details to story board along with summary
  and timelines for the outreach intership program.
  by the students to participate in the Virtual Labs
  internship program.

* Motivation
  This internship program is conducted to motivate students
  from the Nodal center colleges to contribute towards this
  mission mode project run by MHRD. Students would be
  contributing towards the open source development community
  as well as improve the Virtual Labs. The motivation for us
  behind conducting such intenrship program is to do
  outreach activities for the Virtual Labs and improve its
  reach to as many colleges as possible.

* Summary at a glance
 |------+------------+------+--------------|
 | S.no | Activity   | Date | Remarks/link |
 |------+------------+------+--------------|
 |   1. | Mail to NC |      |              |
 
* Timelines
  

* Process
  Link to the process doc

* Draft Mails 
  Draft mail to call for interns
  Draft mail to explain process for Phase 1
  Draft mail to announce selected candidates for Phase 2

* Logistics
  Prize Money
  Support during bootcamp


 


* Issue/Bug logging process - Selection of interns

  [[https://github.com/vlead/outreach-internship-program/blob/develop/src/intern-selection.org][Link for the document]]

* Conclusion
  Based on the issues raised the students would be given an
  opportunity to work as an intern in virtual labs and also contribute
  in a mission mode MHRD project.
  
