#+TITLE: Manual for internship activities
#+AUTHOR: VLEAD
#+DATE: [2018-04-12 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document describes the detailed steps to be followed
  by the students to participate in the Virtual Labs
  internship program.

* Motivation
  This internship program is conducted to motivate students
  from the Nodal center colleges to contribute towards this
  mission mode project run by MHRD. Students would be
  contributing towards the open source development community
  as well as improve the Virtual Labs. The motivation for us
  behind conducting such intenrship program is to do
  outreach activities for the Virtual Labs and improve its
  reach to as many colleges as possible.

* Issue/Bug logging process
  The below sections describe the entire process of raising
  lab issues and what template needs to be followed for the
  same by the interested students.

** Setup of testing environment 
  [[https://vlabs-about.vlabs.ac.in/#sec-4][Click here]] and follow the document to setup the
  development environment.

** Steps to be followed by the students for raising issues
   An interested student needs to test the IIIT Hyderabad
   labs (20 labs). The testing process would be to carried
   out to find the problems with the labs. When any such
   issue is identified

*** Steps to create a new github repository
   1) Login to your github profile and click on repositories
      tab
   2) Click New button(green coloured) for creating new
      repository.
   3) Type Repository name as "virtual-labs-internship"
   3) Add a description of the repository(optional).
   4) choose "Public".
   5) Select Initialize this repository with a README. 
   6) Click Create repository.
*** Parameters to be considered while raising the issues
   a. Operational defects : Broken links, error pages,
   content not visible, buttons not working and any others.

   b. Functional defects : Provided features are not working
   as per the expectations.

   c. Simulations defects :
     - Working Status
     - Quality of simulator
     - Analysis of output
     - Simulations have logical flaws

   d. Enhancements: Quality and clarity of the content
   
   e. New content suggested by the students are also
   welcomed.
   
   f. Every defect/bug logged must follow the SMART
   ideology - Specific, Measurable, Attainable, Realistic
   and Timely

*** Naming convention to be followed while creating issues
    bug_<lab_name>_<in which sub section of experiment the
    bug is detected> for example:
    bug_problem-solving-simulation

*** Description of issue includes the following
    - Defect description
    - Expected result
    - Actual result
    - Screen shot
  
** Labels and severity
    - Lab name : This label indicates that in which lab the
    A issue would contain a brief description and a
    hyper-link to its corresponding test case file. It could
    also contain screen shots for easier
    comprehension. Every defect would contain labels to
    describe its state, severity and category. The following
    are the attributes that would be attached to each
    defect: defect is detected.

    - Experiment name : This label indicates that in which 
    experiment the defect is detected.

    - Sections : In which of the section like introduction, 
    theory, simulation, quiz the issue is detected.

    - Category : At any given time a issue should only have
    one of the categories like Content, UI, functionality.
    
    - Severity : At any given time a issue should only have
    one of the severity levels as described below. To change
    the severity of a issue, the existing label of the issue
    should be unchecked and the new severity label should be
    checked.

      1) S1 : This label indicates that the issue affects
      critical functionality or critical data. Example:
      Prevention of user interaction, corruption of
      database, unfaithful to the semantics of interaction
      and redirection to the error page.

      2) S2 : This label indicates that the issues affects
      major functionality or major data. It could have
      broken links and a field view being inconsistent with
      its specifications. Example: In a form if there is a
      field which is editable but it is not allowing the
      user to edit it.

      3) S3 : This label indicates that the issue affects
      minor functionality or non-critical data. Example:
      Visual imperfections like spelling and grammar,
      alignment, inconsistent terminology, colour, shapes
      and fonts(css properties).

    - Status : At any given time a issue should only be in
    one of the below described states. To change the state
    of a defect, the current status label of the defect
    should be unchecked and the new status label should be
    checked.

    1) Open : This label indicates that when a issue is
    logged and posted for the first time, it would be
    labelled as 'Open'.

    2) In Progress : This label indicates that Open issues
    while being worked upon by the developer would be
    labelled as 'InProgress'.

    3) Fixed : This label indicates that the issue has been
    fixed by the developers in their lab GitHub repository
    but a release has not been for the hosting. Only the
    developers can mark the issue as fixed. They should
    change the status to resolved and include it in their
    release notes when they make a release containing these
    fixes. Test engineers would test only resolved and open
    defects.

    4) Resolved : This label indicates that when 
    developers make necessary code changes and verifies the
    changes then they can label the defect as
    ¡®Resolved¡¯. The developers as well as the lab owners can
    mark the issue as Resolved.

    5) Reopen : This label indicates that if a resolved
    defect surfaces during testing, the test engineer would
    label it as 'Reopen'.

    6) Closed : This label indicates that Resolved defects
    would be labelled as 'Closed' by the test engineers
    after they pass the tests. This label means that the
    defect is resolved, tested and approved.

** List of issues that will not be considered as valid
   - Full Screen button on experiment simulations doesnt
     open in the new tab, instead we have to copy the URL in
     a new browser window in order to open the
     simulations. This is a known issue to us.
   - 
*** Time limit for raising issues
   The logging defects by students will be from 30th April
   onwards till 5th May , 2018
*** Perks and Prize money
  Top students will be awarded with cash award and all the
  students would be given a participation certificate.
* Validation of issues
  
* Conclusion
  Based on the bugs raised the students would be given an
  opportunity to work as a intern in virtual labs.
  
