#+TITLE: Manual for Students
#+AUTHOR: VLEAD
#+DATE: [2018-04-12 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction - Issue/bug/defect/enhancement process
  This document describes the detailed steps to be followed by the
  students to participate in the Virtual Labs internship program.

* Steps to be followed for raising issues/bugs/defects/enhancements
** Step 1
   Create a new gitlab project
   1) Create a GitLab Handle
   2) Steps to create a new gitlab project
      * Login to your gitlab profile and click on New Projects
       button.
      * Give the project name as
        "*virtual-labs-internship-<your name>*".
      * Set the 'Visibility Level' as *Private*.
      * Click on 'Create Project'.
      * Click on "Settings" and then "Members"
      * Give "Select members to invite" as "*outreach-internship*".
      * Set "Choose a role permission" as "*master*".
      * Set the date to "Access expiration date" as "*09 May
        2018*".
      * Click on "*Add to project*".

** Step 2
  1) Click [[www.http://vlabs.ac.in][Virtual Labs website]] and hover on institutes
     option in the header and click on IIIT-Hyderabad to
     access the labs to be tested
  2) Select a lab and start exploring the features of the
     experiments and the related textual content
  3) During the exploration/usage, If you encounter any
     issues such as
   1) *Operational defects* : Broken links, error
      pages,content not visible or incorrect including
      English grammar, buttons not working and any others.
   2) *Simulation defects* :
       + The simulation doesnot work as per the given
         instructions.
       + No instructions given for the simulator.
       + Incorrect display of the output.
       + Logical flaw in the experiment simulation.
       + Quality of simulator can be improved or enhanced.
  4) Log as issues in gitlab
   
 
** Step 3 
   To start logging issues in gitlab
   1) Visit the project that you created.
   2) Click on "Issues", that is just below the overview on the left hand side of your web page.
   3) Click on "New Issue".  
   4) <lab_name>_<experiment_name>_<sub section of
      experiment where the bug is detected>
      - For Example : problem-solving_numerical-representation_objective
   5) Following details must be present in an issue when the problem is
    identified in a lab.
    + Defect description : The description should specify an
      exact problem in the application. 
    + Steps to reproduce the issue : Detail  the steps start
      from the Login step till the defect was found.
    + Expected result :  you can propose what could be done
      to resolve it or done to enhance it in brief.
    + Actual result : descibe what the feature is actually showing
      instead of correct results.
    + Screen shot : screenshot of the defect capturing the screen
      where it was identified
    Please go through this [[https://github.com/virtual-labs/problem-solving-iiith/issues/343][Sample Issue]] for better understanding. 

** Step 4 
   Labels should be created for better identify and
   categorise the issues
   1) Category : At any time an issue could be either of the
      two -
      + *Bug* - This label refers to the problems existing in the
        labs related to  section/sub section of an experiment.
      + *Enhancement* - This label refers to new suggestions for the
        labs which could improve the lab quality.
   2) Type of issues :
      An issue should only be in any one of the types 
      + *Content* - This label refers to the content which is not
        comprehensible or has some mistakes, otherwise a new content
        needs to be added in case of incomplete information.    
      + *UI* - This label refers to the case where there are any user
        interface related problems like broken links or buttons not
        functioning.
      + *Functionality* - This label refers to the issues where the
        features are not working.
   The Severity of the issue/defect/bug should specified at
   "*Weight*". Based on the severity level of the issue select
   the value ranging from *No Weight* to *9*
   
* Step 5         
  The following mentioned issues would be considered invalid
   1) Full Screen button on experiment simulations doesn't
      open in the new tab, instead we have to copy the URL
      in a new browser window in order to open the
      simulations. This is a known issue to us.
   2) We are not focussing on spelling mistakes and
      grammatical errors, even if such issues are raised
      they won't be given any weightage.

* Time limit for raising issues
   You are allowed to log defects till *7th May* 2018, 08:00
   A.M. IST.

* Perks and Prize money
   Top 10 students would be awarded with prizes based on the
   gravity of issues (severity level, functionality defects
   identified, proposal for enhancements and logical flaws)
   identified/logged after our team validates and review.
