#+Title: Outreach Internship Report 
#+Date: [2018-07-17 Tue]
#+PROPERTY: results output
#+PROPERTY: exports code
#+options: ^:nil

* Introduction
  This document captures the overall report for Outreach
  Internship at VLEAD.

* Executive Summary 
  The objective of the outreach internship at VLEAD was to improve the
  existing Virtual Labs of IIITH as well as engage the Nodal Centers
  in the outreach process. It was decided to offer a 6-8 weeks of
  internship program for the selected students to accomplish the same.
  The plan was to hire around 20-30 interns and have them fix the bugs
  which were supposed to be raised as part of their selection
  process. The entire program was divided into 2 phases : 

  + Phase 1 : This included call for the students from 6 different
    nodal centers and giving them a timeline to raise as many issues
    as possible from the IIIT Hyderabad labs. During this process,
    when we couldn't get substantial number of issues raised by the
    students, we conducted a Bugathon at IIIT H which also included
    the participation from MSIT students. After this event, we could
    get 1000+ issues logged which made it a success. Based on the
    quality of issues raised, they were selected for the internship
    program.

  + Phase 2 : This phase included the 3 days Bootcamp training for the
    selected interns. The training was given on GitHub, Javascript and
    Java by the VLEAD outreach team mentors. After the bootcamp,
    interns were expected to work remotely in fixing the issues/bugs
    raised in phase 1 and attend a review meeting every week with the
    VLEAD team for any problems faced.

   |--------+------------------------------+-------------------|
   | Sl No. | Events                       | number            |
   |--------+------------------------------+-------------------|
   |      1 | Participation call           | 6 NCs             |
   |--------+------------------------------+-------------------|
   |      2 | Number of students           | 71                |
   |        | applied through Google       |                   |
   |        | Forms                        |                   |
   |--------+------------------------------+-------------------|
   |      3 | Number of students who       | 118               |
   |        | attended the Bugathon        | 94 MSIT+24 others |
   |--------+------------------------------+-------------------|
   |      4 | Number of issues logged      | 1015              |
   |        | after bugathon               |                   |
   |--------+------------------------------+-------------------|
   |      5 | Number of students selected  | 26                |
   |        | for the internship           | 16 others+11 MSIT |
   |--------+------------------------------+-------------------|
   |      6 | Number of interns who        | 15 (other college |
   |        | attended bootcamp            | students)         |
   |--------+------------------------------+-------------------|
   |      7 | Number of valid issues given | 315               |
   |        | for fixing                   |                   |
   |--------+------------------------------+-------------------|
   |      8 | Number of issues fixed w/o   | 217               |
   |        | 3 validations                |                   |
   |--------+------------------------------+-------------------|
   |      9 | Number of issues fixed with  |                   |
   |        | 3 validations                |                   |
   |--------+------------------------------+-------------------|
   |     10 | Number of issues not fixed   | 100+              |
   |--------+------------------------------+-------------------|
   
* Outreach Internship Details
** Facts 
   [[https://github.com/vlead/outreach-internship-program/blob/develop/src/index.org][Outreach Internship Program]] started off with the following design :
**** Phase 1 details
     + We pitched the idea of involving the Nodal Centers in the
       outreach process at the same time obtaining the required usage
       numbers to the Choppella sir through a presentation. It was a
       pilot project for us as its success would have decided whether
       this model works for a larger number.
     + Once there was a go ahead by Prof. Venkatesh Choppella, we sent
       the invitation mail to all the Nodal Coordinators (6 to be
       precise) explaining them our idea and how it benefit their
       students in terms of work exposure and also to us in terms of
       getting our labs improved.
     + After the initial invites, we didn't see much activity from the
       coordinators for few weeks as there was a disconnect between
       the management of the colleges and their students. Another
       reason was the exam schedule. We learnt that April,May and June
       is the peak time for the semester ending exams in all the
       colleges and the students are busy preparing for that.
     + This made us change our strategy a bit in the way that instead
       of only communicating with the coordinators, we started sending
       reminder mails to the students also once we requested their
       mail ids from their college departments. After students were
       engaged in this communication, the word spread in their college
       and we started seeing good response in terms of google form
       submissions.
     + Another major roadblock came when we expected them to
       understand the selection process which comprised of raising
       bugs after testing the IIIT H labs. Most of the students just
       applied through forms but didn't start raising bugs. Seeing
       this trend for another 3-4 weeks, we were worried that we need
       to have a backup plan in order to raise the bugs and give a
       kick start to this project.
     + This led us to conduct a one day Bugathon @ IIIT H wherein we
       invited all the students who applied for this program whether
       they raised any bugs or not. Along with them we also invited
       MSIT students from IIIT itself to create the environment for a
       healthy competition amongst all.
     + We selected 26 interns from the bugathon process including the
       students who were performing well from the beginning in raising
       the bugs. We also awarded the top performers with cash prizes.
     + This marked the end of Phase 1.
**** Phase II details 
     + We created a 3 day [[https://github.com/vlead/outreach-internship-program/blob/develop/src/phase2/bootcamp/bootcamp-plan.org][Bootcamp session]] for the selected interns
       excluding the MSIT students as they are already in their
       masters program. Total number of interns who attended the
       bootcamp are 15.
     + College wise break up of the interns :
     |--------+-------------------+---------+----------------------------------|
     | Sl.No. | College Name      |  No. of | Names of interns                 |
     |        |                   | interns |                                  |
     |--------+-------------------+---------+----------------------------------|
     |      1 | Vasavi College of |       7 | Saiteja, Aakarsh, Pranay,        |
     |        | Engg.             |         | Divija, Deekshitha, Varsha Reddy |
     |        |                   |         | & Sarika                         |
     |--------+-------------------+---------+----------------------------------|
     |      2 | Chaitanya college |       4 | Sharath, Saikrishna, Shaylaja &  |
     |        |                   |         | Rajeshwari                       |
     |--------+-------------------+---------+----------------------------------|
     |      3 | Sreenidhi College |       2 | Aditya & Rajdattu                |
     |--------+-------------------+---------+----------------------------------|
     |      4 | Anurag College    |       1 | Varsha C                         |
     |--------+-------------------+---------+----------------------------------|
     |      5 | SVNIT, Surat      |       1 | Rashmi G                         |
     |--------+-------------------+---------+----------------------------------|

     + The bootcamp session included the training on GitHub, Java and
       Javascript each day. This was an enriching experience for the
       interns as they became more confident and opened up about their
       capabilites and expectations from us.
     + For the next 5 weeks, all of them were expected to start fixing
       the bugs raised as part of the selection process as well as the
       bugathon event. None of the issues were assinged to any intern
       and they were made independent in choosing any issue they wish
       to start with.
     + Here came an important learning startegy for us where we saw
       the opportunity in deploying the Game theory amongst these
       students. They were only restrained in the part where we would
       score them based on their fixes for the 5 different severity
       level issues. We did not reveal them what our severity
       labelling would be but we still provided them an overview of
       this QA technique as to how the bugs are labelled as S1, S2, S3
       and so on.
***** Weekly description of the internship
      + Week 1 : We added all the interns in the Slack channel for the
        common communication. All the 16 interns started resolving the
        issues raised after the issues were migrated to the respective
        lab repos from their private GitLab accounts. The other MSIT
        selected interns neither responded on the slack nor took
        active participation in this phase. The reason being that they
        were all on their semester vacations.
 
        This week went very well in terms of number of bugs resolved
        but most of them picked up broken link issues only as they
        were least severity level issues. Initially we decided that we
        would also award the weekly top performer with some cash
        prize, but that couldn't happen this week as validation
        process didn't took off very well. On Friday, all of them came
        for their weekly review. Lalit explained the prcoess of
        validation and how could we do it in terms of game theory. It
        was modelled in the way wherein in order to accept a solved
        issue, every resolved issue must have atleast 2 peer
        validation. Peer validation means, one could be from any
        interns amongst themselves and another should be from a
        different college intern amongst themselves.
      + Week 2 : This week also they picked up many issues which were
        S4 and S5 only and started solving them. Weekly review
        happened on Friday again and they shared their challenges in
        terms of getting 2 validations. During this time we as a team
        also thought about a final validation process which would mean
        that the resolved issue can now go into production. This final
        third validation was decided to be done by the inhouse IIIT
        interns.

        We thought of giving this responsibility to them as they were
        all in college campus for the next 2-3 years and we could give
        them this responsibility because they are capable of it as
        well as we can have them responsible if their valid fix is not
        correct after we move the fixes to production. The IIIT
        interns were involved in this week for doing the final
        validations. Initially getting it done from them was a
        challenge as they already had their own tasks, after repeated
        efforts they started doing this task as well. The ADS setup
        was a challenge for all of them but it was resolved
        eventually.

        |--------+---------+----------------|
        | Labels | Meaning | Scores awarded |
        |--------+---------+----------------|
        | S1     |         |                |
        |--------+---------+----------------|
        | S2     |         |                |
        |--------+---------+----------------|
        | S3     |         |                |
        |--------+---------+----------------|
        | S4     |         |                |
        |--------+---------+----------------|
        | S5     |         |                |
        |--------+---------+----------------|
 
      + Week 3 : Here came the milestone week where the fixed issues
        with 2 validations were being finally validated by the IIIT
        interns also and we could start scoring the outreach interns
        based on that. We scored all the interns and it was done based
        on weekly performance of each student. The leaderboard was
        ready and we publishes it on slack this time with the cash
        prizes being given to the top performing students.

        This was the most fruitful week in terms of maximum number of
        S5, S4, S3 issues were fixed by this time and we were only
        left with the high severity issues which were related to
        simulations. This also brought to our notice the
        underperformers as well the strategy of students in this whole
        game. The Sreenidhi interns devised a way that they didn't do
        much fixes but they only focussed on validating others
        fixes. Validations also fetched points to everyone. There were
        penalties awarded to the wrong validations also.

        |-------------------+-----------------|
        | Validations       | Points &        |
        |                   | Penalties       |
        |-------------------+-----------------|
        | First validation  | +1 for correct  |
        |                   | -1 for wrong    |
        |-------------------+-----------------|
        | Second validation | +1 for correct, |
        |                   | -2 for wrong    |
        |-------------------+-----------------|
        | Final validation  | +1 for correct, |
        |                   | -3 for wrong    |
        |-------------------+-----------------|
        
      + Week 4 : The process was ongoing for another week but we
        didn't see any fixes during this week. This time when they
        came for the weekly review, we had a session on shell
        scripting for them. Sarika highlighted the problem where most
        of her fixed issues were still waiting for the 2nd
        validation. At this point of time we realised that since the
        vasavi interns are in majority, getting the second validation
        from other college interns is indeed a challenge for them. It
        was noted and we allowed them to have 2nd validator from the
        same college from this point onwards. No cash award could be
        given for this week as well as we were waiting for the final
        validations by the IIIT interns.
      + Week 5 : This was the most busiest week for all of us as the
        final validations were still in progress by the IIIT
        interns. On the last day (13th July) all the interns came for
        the results and they were announced along with the cash prizes
        for overall top performer, top fixers and top validators. We
        tried to acknowledge all the interns in terms of prizes who
        stood out during the whole journey.

        |--------+------------------------|
        | Sl no. | Students who stood out |
        |--------+------------------------|
        |      1 | Saiteja Kura, Vasavi   |
        |--------+------------------------|
        |      2 | Aakarsh, Vasavi        |
        |--------+------------------------|
        |      3 | Sarika, Vasavi         |
        |--------+------------------------|
        |      4 | Varsha Reddy, Vasavi   |
        |--------+------------------------|
        |      5 | Rajadattu, Sreenidhi   |
        |--------+------------------------|
        

** Summary & Opinions 
   Overall the internship has been fruitful with proof of concept for
   outreach NC engagement along with improvement in the existing
   labs. There are a lot of wrinkles ( duplicacy and plagiarism
   detection ,validation process, automated scoring and labelling )
   that need to be ironed out which can be done before the start of
   next outreach internship program.

   Final leaderboard along with number of S1,S2,S3,S4 and S5 bugs
   fixed overall is given below :
  
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   | Sl No. | Name         | S1 | S2 | S3 | S4 | S5 | Fixes | Validation | Total | Grade        |
   |        |              |    |    |    |    |    | Score |      Score | Score |              |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |      1 | Aakarsh      |  0 | 14 | 10 |  5 |  7 |   103 |         28 |   131 | Excellent    |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |      2 | Kura Saiteja |  1 |  1 | 17 | 10 | 24 |   104 |         18 |   122 | Excellent    |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |      3 | Rajadattu    |  0 |  0 |  0 |  1 | 19 |    21 |         53 |    74 | Good         |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |      4 | Sarika       |  1 |  2 |  6 |  1 |  1 |    34 |         35 |    69 | Excellent    |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |      5 | Varsha Reddy |  1 |  0 |  2 | 16 |  4 |    47 |         16 |    63 | Excellent    |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |      6 | Aditya Goda  |  0 |  0 |  0 |  1 |  3 |     5 |         39 |    44 | Good         |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |      7 | Pranay       |  0 |  0 |  1 |  1 |  5 |    10 |         22 |    32 | Good         |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |      8 | Rashmi       |  0 |  0 |  1 |  4 | 15 |    26 |          3 |    29 | Satisfactory |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |      9 | Deekshitha   |  0 |  0 |  0 |  3 | 20 |    26 |          3 |    29 | Satisfactory |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |     10 | Divija       |  0 |  0 |  0 |  0 |  5 |     5 |         18 |    23 | Satisfactory |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |     11 | Varsha C     |  0 |  0 |  2 |  0 |  4 |    10 |          4 |    14 | Satisfactory |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |     12 | Sharath      |  0 |  0 |  0 |  0 |  0 |     0 |         13 |    13 | Satisfactory |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |     13 | Saikrishna   |  0 |  0 |  0 |  3 |  5 |    11 |          0 |    11 | Satisfactory |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |     14 | Shylaja      |  0 |  0 |  0 |  0 |  0 |     0 |          0 |     0 | Fail         |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   |     15 | Rajeshwari   |  0 |  0 |  0 |  0 |  0 |     0 |          0 |     0 | Fail         |
   |--------+--------------+----+----+----+----+----+-------+------------+-------+--------------|
   

   Testimonials from the students : 

