#+TITLE: Manual for Students
#+AUTHOR: VLEAD
#+DATE: [2018-04-12 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document describes the detailed steps to be followed by the
  students to participate in the Virtual Labs internship program.

* Motivation
  This internship program is conducted to motivate students from the
  Nodal center colleges to contribute towards this mission mode
  project run by MHRD. Students would be contributing towards the open
  source development community as well as improve the Virtual Labs.

* Issue/Bug logging process
  The below sections describe the entire process of raising
  lab issues and what template needs to be followed for the
  same by the interested students.

** Setup of testing environment 
   [[https://vlabs-about.vlabs.ac.in/#sec-4][Click here]] and follow the document to setup the development
   environment.

** Steps to be followed by the students for raising issues

   An interested student needs to test the IIIT Hyderabad labs. The
   testing process would be carried out to find the problems with the
   labs. When any such issue is identified the below process list the
   steps for logging such issues.

*** Link for labs to be tested
    Visit [[https://vlabs.ac.in][Virtual Labs website]] for accessing the IIIT Hyderabad
    labs. You would be testing 20 IIIT hyderabad labs as part of this
    program and raise the issues for the same.

*** Steps to create a new gitlab project
    1) Login to your gitlab profile and click on New Projects
       button.
    2) Give the project name as "virtual-labs-internship".
    3) Write a small description for the project to help you identify
       this activity in future easily.
    4) Choose the Visibility Level as *Private*.
    5) Click on Create Project and create the project.
    6) You can start raising issues/logging bugs in this project now.
 
*** Parameters for raising the issues
    1) *Operational defects* : Broken links, error pages, content not
       visible, buttons not working and any others.

    2) *Functional defects* : Provided features are not working as per
       the expectations.

    3) *Simulation defects* :

       + Working Status - Whether the simulation works as per the
         instructions given. If there are no instructions, scope of
         providing the same.
       + Quality of simulator - Whether the simulations could be
         improved in any way which could make them more engaging for
         the end users.
       + Analysis of output - Whether the outputs displayed are
         correct according to the experiments performed.
       + Simulations having logical flaws - Many labs have been
         identified to have logical flaws in the experiment
         simulations. A great opportunity to resolve them.

    4) *Enhancements* - If the quality and clarity of the content is not
       upto the mark, new content could be suggested to make it more
       comprehensible. Such issues are always welcomed. 
    
    5) Every defect/bug logged should follow the *SMART* ideology -
       Specific, Measurable, Attainable, Realistic and Timely. Refrain
       from identifying spelling mistakes as bugs. They won't be
       considered as issues.

*** Naming convention to be followed while creating issues
    <lab_name>_<experiment_name>_<sub section of experiment where the
    bug is detected>
 
    For Example : problem-solving_numerical-representation_objective

*** How to raise the issues
    Following details must be present in an issue when the problem is
    identified in a lab. Please go through this [[https://github.com/virtual-labs/problem-solving-iiith/issues/343][Sample Issue]] for
    better understanding.

    + Defect description 
      
      Give an abstract of the issue identified in simple words. The
      first few lines should specify an exact problem in the
      application. In the following paragraph mention in detail like
      steps to reproduce (E.g. Start from the Login step till the
      defect was found).  The more elaborate the issue description,
      better it would be to avoid duplications by other students. It
      would be easier to analyse the defect and fix it.

    + Expected result

      It should elaborate the result which you are expecting to see as
      an end user. In this section you can propose what could be done
      to resolve it or done to enhance it in brief.

    + Actual result

      This section should descibe what the feature is actually showing
      instead of correct results. 
    
    + Screen shot

      A small screenshot of the defect capturing the screen
      where it was identified and needs to be resolved.
  
** Labels

   You need to create below described labels in order for us to better
   identify and categorise the issues. Please see this [[https://github.com/virtual-labs/problem-solving-iiith/issues/343][Sample Issue]]
   for a better understanding on labelling the issues.

   1) Category : At any time an issue could be either of the two -

      + *Bug* - This label refers to the problems existing in the
        labs. It could be with any section/sub section of an
        experiment.

      + *Enhancement* - This label refers to new suggestions for the
        labs which could improve the lab quality. For e.g. the
        existing content is not comprehensible, a new content could be
        suggested for the same.

   2) Type of issues :

      At any given time an issue should only be in any one of the
      types 

      + *Content* - This label refers to the content which is not
        comprehensible or has some mistakes, otherwise a new content
        needs to be added in case of incomplete information.
    
      + *UI* - This label refers to the case where there are any user
        interface related problems like broken links or buttons not
        functioning as per the expected results.

      + *Functionality* - This label refers to the issues where the
        features are not working as per expectations. E.g. Simulator
        is not working

*** Severity Labels
    
   At any given time an issue should only have one of the severity
   levels as described below. To change the severity of an issue, the
   existing label of the issue should be unchecked and the new
   severity label should be checked.


   1) *S1* : This label indicates that the issue affects critical
      functionality or critical data. For Example: Prevention of user
      interaction, unfaithful to the semantics of interaction and
      redirection to the error page, logical errors in the experiment
      simulations.

   2) *S2* : This label indicates that the issues affects major
      functionality or major data. It could have broken links and a
      field view being inconsistent with its specifications Example:
      In a form if there is a field which is editable but it is not
      allowing the user to edit it.

   3) *S3* : This label indicates that the issue affects minor
      functionality or non-critical data. Example: Visual
      imperfections like spelling and grammar, alignment, inconsistent
      terminology, colour, shapes and fonts(css properties).

** Issues that would be considered invalid

   1) Full Screen button on experiment simulations doesn't open in the
      new tab, instead we have to copy the URL in a new browser window
      in order to open the simulations. This is a known issue to us.

   2) We are not focussing on spelling mistakes and grammatical
      errors, even if such issues are raised they won't be given any
      weightage.

** Time limit for raising issues
   You are allowed to log defects from *30th April* till *5th May*
   2018, 12:00 A.M. IST.

** Perks and Prize money
   Top 10 students would be awarded with prizes based on the gravity
   of issues (severity level, functionality defects identified,
   proposal for enhancements and logical flaws) identified/logged
   after our team validates and review.

