#+TITLE: Phase 1 : Validation of raised issues
#+AUTHOR: VLEAD
#+DATE: [2018-04-12 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document describes the process followed for validating the
  issues raised by the students in the phase 1.

* Plan of action
  The deadline for submitting the application forms is 7th May 2018,
  8:00 a.m. IST. This means that by that time all the interested
  students would have logged all the defects in their own gitLab
  profiles. The following steps would be carried as described below :

  + VLEAD team (Lalit, Sanchita, Mrudhvika and Gayatri) is the core
    team which would carry out the tasks of mentoring, reviewing and
    validating the issues raised as well resolved later in the further
    phases.
  + For phase 1 validation, criteria has been designed to select the
    issues raised by all the students based on the certain parameters.
  + The selected issues would be pulled out from the students profiles
    and put in a single repository in Github along with their labels
    and all the content. (automated script required)
  + Once the issues are put in a single bucket, an automated script
    would filter out the issues which are duplicates or refer to
    spelling mistakes. Other parameters to filter are described in
    detail in sections below.
  + After the issues are filtered out and selected for the phase 2,
    they would be migrated to the respective lab repositories in
    Github. (automated script required)
  + These issues would now be labelled as *open* for the selected
    interns to resolve.

* Validation and review process
  Once the process of raising the issues is finished validating
  them has to be done. The following are the proposed
  methodologies for validating issues
** Methodology 1
   
** Methodology 2

* Conclusion
  After the validation process, the issues would be finalized and the
  students would pick them up for resolving them.
  

